<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 父项目信息 -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <!-- 父项目坐标 -->
    <groupId>cn.minglg.interview</groupId>
    <artifactId>interview-app</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>interview-app</name>
    <description>AI模拟面试系统 - 父项目</description>

    <!-- 子模块 -->
    <modules>
        <module>interview-app-webmvc</module>
        <module>interview-app-webflux</module>
    </modules>

    <!-- 项目信息 -->
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

    <!-- 全局属性 -->
    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <!-- 依赖版本管理 -->
        <mybatis.plus.starter.version>3.5.12</mybatis.plus.starter.version>
        <mybatis.spring.version>3.0.5</mybatis.spring.version>
        <druid.starter.version>1.2.23</druid.starter.version>
        <minio.version>8.5.17</minio.version>
        <apache.tika.version>3.1.0</apache.tika.version>
        <apache.commons.lang3.version>3.18.0</apache.commons.lang3.version>
        <hutool.version>5.8.39</hutool.version>
    </properties>


    <!-- 依赖管理 -->
    <dependencyManagement>
        <dependencies>
            <!-- 子模块依赖管理 -->
            <dependency>
                <groupId>cn.minglg.interview</groupId>
                <artifactId>interview-app-webmvc</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.minglg.interview</groupId>
                <artifactId>interview-app-webflux</artifactId>
                <version>${project.version}</version>
            </dependency>


            <!--hutool工具包管理-->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-bom</artifactId>
                <version>${hutool.version}</version>
                <type>pom</type>
                <!-- 注意这里是import -->
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- 构建配置 -->
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <encoding>${project.build.sourceEncoding}</encoding>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <configuration>
                        <encoding>${project.build.sourceEncoding}</encoding>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <encoding>${project.build.sourceEncoding}</encoding>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
