# 项目运行端口
server:
  port: 8081
#  tomcat:
#    max-http-response-header-size: 16KB

# actuator观测指标
management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: '*'


spring:
  application:
    name: interview-app
  banner:
    location: classpath:banner/banner.txt

  #   数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_JDBC_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    type: com.alibaba.druid.pool.DruidDataSource
  #    druid:
  #      #       连接池核心配置
  #      #       最大连接数
  #      max-active: 10
  #      #       初始连接数
  #      initial-size: 5
  #      #       最小空闲连接
  #      min-idle: 5

  # redis配置
  data:
    #    基本配置
    redis:
      cluster:
        nodes:
          - ${REDIS_HOST}:8376
          - ${REDIS_HOST}:8377
          - ${REDIS_HOST}:8378
          - ${REDIS_HOST}:8379
          - ${REDIS_HOST}:8380
          - ${REDIS_HOST}:8381
        max-redirects: 3
      #      超时时间（毫秒）
      connect-timeout: 5000
      #      密码
      password: ${REDIS_PASSWORD}
      #      连接池配置
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  #        cluster:
  #          refresh:
  #            adaptive: true
  #            period: 2000
  #            dynamic-refresh-sources: true

  # 文件上传参数
  servlet:
    multipart:
      # 单个文件最大大小为5MB
      max-file-size: 5MB
      # 单次请求最大总大小（多个文件）
      max-request-size: 20MB

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 开启懒加载配置
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml


# 全局配置
global:
  # 认证信息相关
  auth:
    # 登录请求超时时间（秒）
    request-timeout-seconds: 5
    # jwt/redis过期时间（分）
    jwt-expiration-minutes: 30
    # 登录认证信息存储在redis中的key前缀
    auth-key-prefix: user:security:login
    # 登录页
    login-uri: /api/auth/login
    # 退出页
    logout-uri: /api/auth/logout
  # 不会被JWT拦截的请求路径（白名单，支持通配符表达式）
  white-list-patterns:
    - /api/auth/login         # 登录页
    - /api/auth/register      # 注册页
    - /api/auth/publicKey     # 获取公钥
    - /api/auth/captcha       # 验证码
    - /actuator/**            # 可观测性监控
  # 验证码信息
  captcha:
    # 验证码宽度
    width: 120
    # 验证码高度
    height: 40
    # 验证码数字个数
    code-count: 4
    # 干扰元素个数
    thickness: 10
    # 随机字符序列（当验证码生成器为RandomGenerator时有效，不配置默认为26位大小写字母+10位数字组合）
    # baseStr:
    # 验证码生成器（用于条件注解，不配置默认是cn.hutool.captcha.generator.MathGenerator）
    code-generator: cn.hutool.captcha.generator.MathGenerator
    # 保存在redis中的key前缀
    redis-key-prefix: user:captcha
    # redis中保存key的过期时间
    redis-key-expire-minutes: 5
    # 需要使用验证码的请求路径
    effective-patterns:
      - /api/auth/login
      - /api/auth/register

  # 注册相关
  register:
    # redis中保存的所有角色字典信息的key前缀
    role-redis-key-prefix: role:list
    # 不允许注册的角色列表
    not-allow-roles:
      - ROLE_ADMIN

  # 简历相关
  resume:
    # 文件类型白名单（仅允许以下类型的文件上传）
    allow-file-types:
      - .pdf
      - .doc
      - .docx
      - .txt
    # 简历保存在redis中的简历文件名的key前缀
    resume-redis-key-prefix: resume:resume-upload
    # 简历解析器选择策略，不配置默认是auto（fast/accurate/auto）
    parser-strategy: auto

  # minio文件存储相关
  minio:
    # minio服务API地址
    endpoint: ${MINIO_ENDPOINT}
    # 管理员账户
    access-key: ${MINIO_ACCESS_KEY}
    # 管理员密码
    secret-key: ${MINIO_SECRET_KEY}
    # 桶信息（map集合）
    bucket-name:
      resumeUpload: resume-upload








