DROP TABLE IF EXISTS t_jobs;
-- 岗位信息表
CREATE TABLE IF NOT EXISTS t_jobs
(
    job_id               BIGINT                                                  NOT NULL AUTO_INCREMENT COMMENT '岗位ID(自增主键)',
    company_id           BIGINT                                                  NOT NULL COMMENT '企业ID',
    hr_user_id           BIGINT                                                  NOT NULL COMMENT '发布HR用户ID',
    job_title            VARCHAR(100)                                            NOT NULL COMMENT '岗位标题',
    job_type             ENUM ('FULL_TIME', 'PART_TIME', 'INTERNSHIP')           NOT NULL DEFAULT 'FULL_TIME' COMMENT '工作类型(全职/兼职/实习)',
    job_level            ENUM ('JUNIOR', 'MIDDLE', 'SENIOR', 'EXPERT')           NOT NULL DEFAULT 'MIDDLE' COMMENT '岗位级别(初级/中级/高级/专家)',
    department           VARCHAR(100)                                            NOT NULL COMMENT '所属部门',
    work_location        VARCHAR(200)                                            NOT NULL COMMENT '工作地点',
    salary_min           DECIMAL(10, 2)                                          NULL COMMENT '最低薪资(万元/年)',
    salary_max           DECIMAL(10, 2)                                          NULL COMMENT '最高薪资(万元/年)',
    salary_range         VARCHAR(10)                                             NULL COMMENT '薪资范围',
    experience_years     INT                                                     NOT NULL DEFAULT 0 COMMENT '要求工作年限',
    education_level      ENUM ('HIGH_SCHOOL', 'BACHELOR', 'POSTGRADUATE', 'PHD') NOT NULL DEFAULT 'BACHELOR' COMMENT '最低学历要求',
    job_description      TEXT                                                    NOT NULL COMMENT '岗位描述',
    job_requirements     TEXT                                                    NOT NULL COMMENT '岗位要求',
    job_responsibilities TEXT                                                    NULL COMMENT '工作职责',
    benefits             TEXT                                                    NULL COMMENT '福利待遇',
    contact_info         VARCHAR(500)                                            NULL COMMENT '联系方式',
    application_deadline DATE                                                    NULL COMMENT '申请截止日期',
    status               ENUM ('DRAFT', 'PUBLISHED', 'CLOSED', 'EXPIRED')        NOT NULL DEFAULT 'DRAFT' COMMENT '岗位状态(草稿/已发布/已关闭/已过期)',
    view_count           INT                                                     NOT NULL DEFAULT 0 COMMENT '浏览次数',
    application_count    INT                                                     NOT NULL DEFAULT 0 COMMENT '申请次数',
    is_featured          BOOLEAN                                                 NOT NULL DEFAULT FALSE COMMENT '是否推荐岗位',
    is_urgent            BOOLEAN                                                 NOT NULL DEFAULT FALSE COMMENT '是否紧急岗位',
    tags                 VARCHAR(500)                                            NULL COMMENT '岗位标签(逗号分隔)',
    created_time         TIMESTAMP                                               NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time         TIMESTAMP                                               NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    published_time       TIMESTAMP                                               NULL COMMENT '发布时间',
    closed_time          TIMESTAMP                                               NULL COMMENT '关闭时间',
    PRIMARY KEY (job_id),
    INDEX idx_company_id (company_id) COMMENT '企业ID索引',
    INDEX idx_hr_user_id (hr_user_id) COMMENT 'HR用户ID索引',
    INDEX idx_job_title (job_title) COMMENT '岗位标题索引',
    INDEX idx_job_type (job_type) COMMENT '工作类型索引',
    INDEX idx_job_level (job_level) COMMENT '岗位级别索引',
    INDEX idx_department (department) COMMENT '部门索引',
    INDEX idx_work_location (work_location) COMMENT '工作地点索引',
    INDEX idx_status (status) COMMENT '岗位状态索引',
    INDEX idx_experience_years (experience_years) COMMENT '工作年限索引',
    INDEX idx_education_level (education_level) COMMENT '学历要求索引',
    INDEX idx_salary_range (salary_range) COMMENT '薪资范围索引',
    INDEX idx_is_featured (is_featured) COMMENT '推荐岗位索引',
    INDEX idx_is_urgent (is_urgent) COMMENT '紧急岗位索引',
    INDEX idx_created_time (created_time) COMMENT '创建时间索引',
    INDEX idx_published_time (published_time) COMMENT '发布时间索引',
    INDEX idx_company_status (company_id, status) COMMENT '企业岗位状态复合索引',
    INDEX idx_location_status (work_location, status) COMMENT '地点状态复合索引',
    INDEX idx_type_level_status (job_type, job_level, status) COMMENT '类型级别状态复合索引',
    UNIQUE KEY uk_company_job_title (company_id, job_title) COMMENT '同一企业岗位标题唯一索引'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT = '岗位信息表'; 