spring:
  # redis配置
  data:
    #    基本配置
    redis:
      cluster:
        nodes:
          - ${REDIS_NODE_1}
          - ${REDIS_NODE_2}
          - ${REDIS_NODE_3}
          - ${REDIS_NODE_4}
          - ${REDIS_NODE_5}
          - ${REDIS_NODE_6}
        max-redirects: 3
      #      超时时间（毫秒）
      connect-timeout: 5000
      #      密码
      password: ${REDIS_PASSWORD}
      #      连接池配置
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms