# 项目运行端口
server:
  port: 8081

# actuator观测指标
management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: '*'

spring:
  application:
    name: interview-app-webmvc
  banner:
    location: classpath:banner/banner.txt
  profiles:
    active: dev

  # nacos配置中心
  cloud:
    nacos:
      server-addr: minglg.cn:10845
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
  config:
    import:
      - nacos:nacos-${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true